default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: to_do

test:
  <<: *default
  database: to_do_test

production:
  <<: *default
  database: to_do_production
